name: Publish

on: push
jobs:
  shellLint:
    name: Shell Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install
      uses: actions/npm@master
      with:
        args: install
    - name: Build
      uses: actions/npm@master
      with:
        args: run build
    - name: Test Source
      uses: actions/npm@master
      with:
        args: test
    - name: Test Build
      uses: actions/npm@master
      with:
        args: testvn
    - name: Publish Filter
      uses: actions/bin/filter@master
      with:
        args: branch master
    - name: Publish
      uses: mikeal/merge-release@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
